/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ub.prog2.OrdonezVivancosHector.vista;

import edu.ub.prog2.OrdonezVivancosHector.controlador.CtrlVisorUB;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Héctor Ordóñez
 */
public class MenuRecuperar extends javax.swing.JDialog {
    CtrlVisorUB controlador;
    /**
     * Constructor de MenuRecuperar
     */
    public MenuRecuperar(java.awt.Frame parent, boolean modal, CtrlVisorUB control) {
        super(parent, modal);
        controlador = control;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNomFitxer = new javax.swing.JTextField();
        btnSelecciona = new javax.swing.JButton();
        btnRecupera = new javax.swing.JButton();
        btnCancela = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Recuperar");

        txtNomFitxer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomFitxerActionPerformed(evt);
            }
        });

        btnSelecciona.setText("Selecciona");
        btnSelecciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionaActionPerformed(evt);
            }
        });

        btnRecupera.setText("Recupera");
        btnRecupera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperaActionPerformed(evt);
            }
        });

        btnCancela.setText("Cancel·la");
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNomFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelecciona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnRecupera)
                .addGap(46, 46, 46)
                .addComponent(btnCancela)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecciona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecupera)
                    .addComponent(btnCancela))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
                            /**
    * Action Performed del Text Field que guarda el camí
    * 
    */ 
    private void txtNomFitxerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomFitxerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomFitxerActionPerformed
                         /**
    * Action Performed del botó que serveix per indicar el camí on s'ha de recuperar l'arxiu
    * 
    */
    private void btnSeleccionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionaActionPerformed
        File fitxer;
        //Creació del selector de fitxer
        JFileChooser seleccio = new JFileChooser();
        //Mostrem la finestra de dialeg
        //Resultat emmagazema una constant que indica si s’ha
        //seleccionat o no un fitxer
        int resultat = seleccio.showOpenDialog(this);
        //Assegurem que hi hagi un fitxer seleccionat
        if (resultat == JFileChooser.APPROVE_OPTION) {
            //Obtenim el fitxer
            fitxer=seleccio.getSelectedFile();
            //Posem la ruta del fitxer al quadre de text
            txtNomFitxer.setText(fitxer.toString());
        }
    }//GEN-LAST:event_btnSeleccionaActionPerformed
                         /**
    * Action Performed del boto que serveix per recuperar totes les dades en un arxiu on indiqui el cami
    * 
    */
    private void btnRecuperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperaActionPerformed
                  // TODO add your handling code here:
        try {        
                controlador.recuperarFitxer(txtNomFitxer.getText());
                this.dispose();
        } catch (FileNotFoundException ex) {
            System.out.println("[Fitxer no trobat]");
            //Logger.getLogger(VisorUB1B.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            System.out.println("[IOException error]");
            //Logger.getLogger(VisorUB1B.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            System.out.println("[Classe no trobada]");      
            //Logger.getLogger(VisorUB1B.class.getName()).log(Level.SEVERE, null, ex);
                    }
    }//GEN-LAST:event_btnRecuperaActionPerformed
                         /**
    * Action Performed del boto Cancela que tanca la finestra
    * 
    */
    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelaActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancela;
    private javax.swing.JButton btnRecupera;
    private javax.swing.JButton btnSelecciona;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNomFitxer;
    // End of variables declaration//GEN-END:variables
}
