/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ub.prog2.OrdonezVivancosHector.vista;

import edu.ub.prog2.OrdonezVivancosHector.controlador.CtrlVisorUB;
import edu.ub.prog2.OrdonezVivancosHector.model.Album;
import edu.ub.prog2.OrdonezVivancosHector.model.Excepcio;
import edu.ub.prog2.OrdonezVivancosHector.model.FitxerImatge;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author Héctor
 */
public class VisorUB5 extends javax.swing.JFrame {
    CtrlVisorUB controlador;
    /**
     * Constructor new form VisorUB5
     */
    public VisorUB5() {
        controlador = new CtrlVisorUB();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRepro = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        btnAfegirBiblioteca = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnEliminarBiblioteca = new javax.swing.JButton();
        btnVisualitzarImatgeBiblioteca = new javax.swing.JButton();
        btnPlayBiblioteca = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        llstBiblioteca = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jScrollBar2 = new javax.swing.JScrollBar();
        jLabel2 = new javax.swing.JLabel();
        btnEliminarAlbum = new javax.swing.JButton();
        btnCrearAlbum = new javax.swing.JButton();
        btnAfegirImatgeAlbum = new javax.swing.JButton();
        btnEliminarImatgeAlbum = new javax.swing.JButton();
        btnVisualitzarImatgeAlbum = new javax.swing.JButton();
        btnPlayAlbum = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        llstAlbums = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnRecuperar = new javax.swing.JButton();
        jScrollBar3 = new javax.swing.JScrollBar();
        jLabel3 = new javax.swing.JLabel();
        jTemps = new javax.swing.JSlider();
        chkReproSequencial = new javax.swing.JRadioButton();
        chkReproAleatoria = new javax.swing.JRadioButton();
        btnPausar = new javax.swing.JButton();
        btnReprendre = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        llstImatgesAlbum = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnParar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(85, 248, 85));

        jPanel1.setBackground(new java.awt.Color(205, 0, 255));
        jPanel1.setForeground(new java.awt.Color(115, 13, 13));

        jScrollBar1.setBackground(new java.awt.Color(71, 4, 90));

        btnAfegirBiblioteca.setBackground(new java.awt.Color(71, 4, 90));
        btnAfegirBiblioteca.setForeground(new java.awt.Color(255, 255, 255));
        btnAfegirBiblioteca.setText("Afegir");
        btnAfegirBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirBibliotecaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Biblioteca");

        btnEliminarBiblioteca.setBackground(new java.awt.Color(71, 4, 90));
        btnEliminarBiblioteca.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarBiblioteca.setText("Eliminar");
        btnEliminarBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarBibliotecaActionPerformed(evt);
            }
        });

        btnVisualitzarImatgeBiblioteca.setBackground(new java.awt.Color(71, 4, 90));
        btnVisualitzarImatgeBiblioteca.setForeground(new java.awt.Color(255, 255, 255));
        btnVisualitzarImatgeBiblioteca.setText("Visualitzar Imatge");
        btnVisualitzarImatgeBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualitzarImatgeBibliotecaActionPerformed(evt);
            }
        });

        btnPlayBiblioteca.setBackground(new java.awt.Color(71, 4, 90));
        btnPlayBiblioteca.setForeground(new java.awt.Color(255, 255, 255));
        btnPlayBiblioteca.setText("Visualitzar Biblioteca");
        btnPlayBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayBibliotecaActionPerformed(evt);
            }
        });

        llstBiblioteca.setBackground(new java.awt.Color(237, 77, 231));
        jScrollPane5.setViewportView(llstBiblioteca);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnVisualitzarImatgeBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(btnPlayBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAfegirBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAfegirBiblioteca)
                    .addComponent(btnEliminarBiblioteca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVisualitzarImatgeBiblioteca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlayBiblioteca)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 247, 37));
        jPanel2.setForeground(new java.awt.Color(254, 255, 39));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Àlbums");

        btnEliminarAlbum.setBackground(new java.awt.Color(255, 208, 12));
        btnEliminarAlbum.setText("Eliminar");
        btnEliminarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAlbumActionPerformed(evt);
            }
        });

        btnCrearAlbum.setBackground(new java.awt.Color(255, 208, 12));
        btnCrearAlbum.setText("Crear");
        btnCrearAlbum.setToolTipText("");
        btnCrearAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearAlbumActionPerformed(evt);
            }
        });

        btnAfegirImatgeAlbum.setBackground(new java.awt.Color(255, 208, 12));
        btnAfegirImatgeAlbum.setText("Afegir Imatge");
        btnAfegirImatgeAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirImatgeAlbumActionPerformed(evt);
            }
        });

        btnEliminarImatgeAlbum.setBackground(new java.awt.Color(255, 208, 12));
        btnEliminarImatgeAlbum.setText("Eliminar Imatge");
        btnEliminarImatgeAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarImatgeAlbumActionPerformed(evt);
            }
        });

        btnVisualitzarImatgeAlbum.setBackground(new java.awt.Color(255, 208, 12));
        btnVisualitzarImatgeAlbum.setText("Visualitzar Imatge");
        btnVisualitzarImatgeAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualitzarImatgeAlbumActionPerformed(evt);
            }
        });

        btnPlayAlbum.setBackground(new java.awt.Color(255, 208, 12));
        btnPlayAlbum.setText("Visualitzar Àlbum");
        btnPlayAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayAlbumActionPerformed(evt);
            }
        });

        llstAlbums.setBackground(new java.awt.Color(248, 240, 126));
        llstAlbums.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chkLlistAlbumPress(evt);
            }
        });
        jScrollPane4.setViewportView(llstAlbums);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnPlayAlbum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                .addComponent(btnVisualitzarImatgeAlbum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                .addComponent(btnEliminarImatgeAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                .addComponent(btnAfegirImatgeAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(btnCrearAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEliminarAlbum)
                            .addGap(14, 14, 14))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 12, Short.MAX_VALUE)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addComponent(jScrollBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearAlbum)
                    .addComponent(btnEliminarAlbum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAfegirImatgeAlbum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarImatgeAlbum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVisualitzarImatgeAlbum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlayAlbum)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(230, 8, 8));

        jPanel4.setBackground(new java.awt.Color(187, 48, 48));

        btnGuardar.setBackground(new java.awt.Color(112, 0, 0));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnRecuperar.setBackground(new java.awt.Color(112, 0, 0));
        btnRecuperar.setForeground(new java.awt.Color(255, 255, 255));
        btnRecuperar.setText("Recuperar");
        btnRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRecuperar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRecuperar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Imatges de l'àlbum");

        jTemps.setBackground(new java.awt.Color(230, 8, 8));
        jTemps.setMaximum(5000);
        jTemps.setMinimum(1000);
        jTemps.setToolTipText("");
        jTemps.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        chkReproSequencial.setBackground(new java.awt.Color(230, 8, 8));
        btnRepro.add(chkReproSequencial);
        chkReproSequencial.setSelected(true);
        chkReproSequencial.setText("Reproducció Seqüencial");
        chkReproSequencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkReproSequencialActionPerformed(evt);
            }
        });

        chkReproAleatoria.setBackground(new java.awt.Color(230, 8, 8));
        btnRepro.add(chkReproAleatoria);
        chkReproAleatoria.setText("Reproduccó Aleatòria");
        chkReproAleatoria.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkReproAleatoriaStateChanged(evt);
            }
        });
        chkReproAleatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkReproAleatoriaActionPerformed(evt);
            }
        });

        btnPausar.setBackground(new java.awt.Color(171, 0, 0));
        btnPausar.setText("Pausar");
        btnPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausarActionPerformed(evt);
            }
        });

        btnReprendre.setBackground(new java.awt.Color(171, 0, 0));
        btnReprendre.setText("Reprendre");
        btnReprendre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReprendreActionPerformed(evt);
            }
        });

        llstImatgesAlbum.setBackground(new java.awt.Color(219, 75, 75));
        jScrollPane2.setViewportView(llstImatgesAlbum);

        jLabel4.setText("1000");

        jLabel5.setText("5000");

        btnParar.setBackground(new java.awt.Color(171, 0, 0));
        btnParar.setText("Parar");
        btnParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chkReproSequencial)
                    .addComponent(chkReproAleatoria)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnParar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(btnPausar, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnReprendre))))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTemps, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(jScrollBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTemps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkReproSequencial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkReproAleatoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPausar)
                    .addComponent(btnReprendre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnParar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
                         /**
    * Action Performed del boto que serveix per crear un nou àlbum obrint MenuCrearAlbum
    * 
    */
    private void btnCrearAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearAlbumActionPerformed
        MenuCrearAlbum dialog = new MenuCrearAlbum(this,true,controlador);
        //Titol de la finestra
        dialog.setTitle("Crear");
        //Mostra la finestra
        dialog.pack();
        dialog.setVisible(true);
        omplirLlistaAlbums();
    }//GEN-LAST:event_btnCrearAlbumActionPerformed
                         /**
    * Action Performed del boto que serveix per afegir un fitxer a la biblioteca obrint FrmAfegirFitxer
    * 
    */
    private void btnAfegirBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirBibliotecaActionPerformed
        FrmAfegirFitxer dialog = new FrmAfegirFitxer(this,true,controlador);
        //Titol de la finestra
        dialog.setTitle("Afegir");
        //Mostra la finestra
        dialog.pack();
        dialog.setVisible(true);
        omplirLlistaBiblioteca();
        for(Object item:  llstAlbums.getSelectedValues()){
                Album elementSeleccionat = (Album) item;
                    omplirLlistaImatgesAlbums(elementSeleccionat);
                }
    }//GEN-LAST:event_btnAfegirBibliotecaActionPerformed
                         /**
    * Action Performed del boto que serveix per borrar l'arxiu seleccionat de la biblioteca
    * 
    */
    private void btnEliminarBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarBibliotecaActionPerformed
            for(Object item: llstBiblioteca.getSelectedValues()){
                FitxerImatge elementSeleccionat = (FitxerImatge) item;
                controlador.eliminarImatge(elementSeleccionat.getId());
            }
            omplirLlistaBiblioteca();
            buidarLlistaImatgesAlbums();
            for(Object item:  llstAlbums.getSelectedValues()){
                Album elementSeleccionat = (Album) item;
                    omplirLlistaImatgesAlbums(elementSeleccionat);
                }
    }//GEN-LAST:event_btnEliminarBibliotecaActionPerformed
                         /**
    * Action Performed del boto que serveix per visualitzar el fitxer seleccionat
    * 
    */
    private void btnVisualitzarImatgeBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualitzarImatgeBibliotecaActionPerformed
         for(Object item: llstBiblioteca.getSelectedValues()){
            try {
                FitxerImatge elementSeleccionat = (FitxerImatge) item;
                controlador.visualitzarException(elementSeleccionat);
            } catch (Excepcio ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnVisualitzarImatgeBibliotecaActionPerformed
                         /**
    * Action Performed del boto que serveix per visualitzar tota la biblioteca
    * 
    */
    private void btnPlayBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayBibliotecaActionPerformed
        controlador.setTimer(jTemps.getValue());
        controlador.visualitzarTot();
    }//GEN-LAST:event_btnPlayBibliotecaActionPerformed
                         /**
    * Action Performed del boto que serveix per guardar en un arxiu obrint MenuGuardar
    * 
    */
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        MenuGuardar dialog = new MenuGuardar(this,true,controlador);
        //Titol de la finestra
        dialog.setTitle("Guardar");
        //Mostra la finestra
        dialog.pack();
        dialog.setVisible(true);
        omplirLlistaBiblioteca();
        omplirLlistaAlbums();
        buidarLlistaImatgesAlbums();
    }//GEN-LAST:event_btnGuardarActionPerformed
                         /**
    * Action Performed del boto que serveix per recuperar en un arxiu obrint MenuRecuperar
    * 
    */
    private void btnRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarActionPerformed
        MenuRecuperar dialog = new MenuRecuperar(this,true,controlador);
        //Titol de la finestra
        dialog.setTitle("Recuperar");
        //Mostra la finestra
        dialog.pack();
        dialog.setVisible(true);
        omplirLlistaBiblioteca();
        omplirLlistaAlbums();
        buidarLlistaImatgesAlbums();
    }//GEN-LAST:event_btnRecuperarActionPerformed
                         /**
    * Action Performed del checkButon que activa la reproduccio sequencial
    * 
    */
    private void chkReproSequencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkReproSequencialActionPerformed
        controlador.activarVisualitzarSequencial();
                
    }//GEN-LAST:event_chkReproSequencialActionPerformed
                         /**
    * Action Performed del checkButon que activa la reproduccio aleatoria
    * 
    */
    private void chkReproAleatoriaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkReproAleatoriaStateChanged
        controlador.activarVisualitzacioAleatoria();
      
    }//GEN-LAST:event_chkReproAleatoriaStateChanged
                             /**
    * Pressed del JList que activa omplir la llista d albums
    * 
    */
    private void llstAlbumsPressed(java.awt.event.MouseEvent evt) {
        for(Object item: llstAlbums.getSelectedValues()){
                Album elementSeleccionat = (Album) item;
                omplirLlistaImatgesAlbums(elementSeleccionat);
        } 
        omplirLlistaAlbums();
    }
                             /**
    * Action Performed del botó EliminarAlbum que borra el element seleccionat en l album
    * 
    */
    private void btnEliminarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAlbumActionPerformed
            for(Object item:  llstAlbums.getSelectedValues()){
                Album elementSeleccionat = (Album) item;
                controlador.eliminarAlbum(elementSeleccionat.getNom());
                
            }
            omplirLlistaAlbums();
            buidarLlistaImatgesAlbums();
    }//GEN-LAST:event_btnEliminarAlbumActionPerformed
                             /**
    * Action Performed del botó afegirImatge que afegeix una imatge de la biblioteca a l'album  seleccionat
    * 
    */
    private void btnAfegirImatgeAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirImatgeAlbumActionPerformed
            for(Object item:  llstAlbums.getSelectedValues()){
                Album elementSeleccionat = (Album) item;
                for(Object item2: llstBiblioteca.getSelectedValues()){
                    FitxerImatge elementSeleccionat2 = (FitxerImatge) item2;
                    controlador.afegirImatgeAlbum(elementSeleccionat.getNom(), elementSeleccionat2.getId());
                    omplirLlistaAlbums();
                    omplirLlistaImatgesAlbums(elementSeleccionat);
                }
           }
    }//GEN-LAST:event_btnAfegirImatgeAlbumActionPerformed
                             /**
    * Action Performed del botó que visualitza una imatge de l album seleccionat
    * 
    */
    private void btnVisualitzarImatgeAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualitzarImatgeAlbumActionPerformed
            controlador.setTimer(jTemps.getValue());      
            for(Object item: llstImatgesAlbum.getSelectedValues()){
                try {
                    FitxerImatge elementSeleccionat = (FitxerImatge) item;
                    controlador.visualitzarException(elementSeleccionat);
                } catch (Excepcio ex) {
                    System.out.println(ex.getMessage());
                }
        }
    }//GEN-LAST:event_btnVisualitzarImatgeAlbumActionPerformed
                             /**
    * Action Performed del botó que visualitza l album seleccionat
    * 
    */
    private void btnPlayAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayAlbumActionPerformed
        controlador.setTimer(jTemps.getValue()); 
        for(Object item:  llstAlbums.getSelectedValues()){
                Album elementSeleccionat = (Album) item;
                controlador.visualitzarAlbum(elementSeleccionat.getNom());
                
            }
    }//GEN-LAST:event_btnPlayAlbumActionPerformed
                             /**
    * Action Performed del botó que elimina una imatge de l album seleccionat
    * 
    */
    private void btnEliminarImatgeAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarImatgeAlbumActionPerformed
        for(Object item:  llstAlbums.getSelectedValues()){
                Album elementSeleccionat = (Album) item;
                for(Object item2: llstImatgesAlbum.getSelectedValues()){
                    FitxerImatge elementSeleccionat2 = (FitxerImatge) item2;
                    controlador.eliminarImatgeAlbum(elementSeleccionat.getNom(), elementSeleccionat2.getId());
                }
           }
        for(Object item:  llstAlbums.getSelectedValues()){
                Album elementSeleccionat3 = (Album) item;
                omplirLlistaImatgesAlbums(elementSeleccionat3);
           } 
        omplirLlistaAlbums();
    }//GEN-LAST:event_btnEliminarImatgeAlbumActionPerformed
                             /**
    * Press de la llista d albums, que la renova cada cop que es presiona
    * 
    */
    private void chkLlistAlbumPress(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkLlistAlbumPress
        for(Object item:  llstAlbums.getSelectedValues()){
                        Album elementSeleccionat3 = (Album) item;
                        omplirLlistaImatgesAlbums(elementSeleccionat3);
                } 
    }//GEN-LAST:event_chkLlistAlbumPress
                             /**
    * Action Performed del botó que pausa la visualitzacio
    * 
    */
    private void btnPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausarActionPerformed
        controlador.setEngegat(false);
    }//GEN-LAST:event_btnPausarActionPerformed
                             /**
    * Action Performed del botó que repren la visualitzacio
    * 
    */
    private void btnReprendreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReprendreActionPerformed
       controlador.setEngegat(true);
    }//GEN-LAST:event_btnReprendreActionPerformed
                             /**
    * Action Performed del check aleatori
    * 
    */
    private void chkReproAleatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkReproAleatoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkReproAleatoriaActionPerformed
                             /**
    * Action Performed del botó que parar que para la reproduccio
    * 
    */
    private void btnPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararActionPerformed
        controlador.pararReproduccio();
    }//GEN-LAST:event_btnPararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisorUB5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisorUB5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisorUB5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisorUB5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VisorUB5().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfegirBiblioteca;
    private javax.swing.JButton btnAfegirImatgeAlbum;
    private javax.swing.JButton btnCrearAlbum;
    private javax.swing.JButton btnEliminarAlbum;
    private javax.swing.JButton btnEliminarBiblioteca;
    private javax.swing.JButton btnEliminarImatgeAlbum;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnParar;
    private javax.swing.JButton btnPausar;
    private javax.swing.JButton btnPlayAlbum;
    private javax.swing.JButton btnPlayBiblioteca;
    private javax.swing.JButton btnRecuperar;
    private javax.swing.JButton btnReprendre;
    private javax.swing.ButtonGroup btnRepro;
    private javax.swing.JButton btnVisualitzarImatgeAlbum;
    private javax.swing.JButton btnVisualitzarImatgeBiblioteca;
    private javax.swing.JRadioButton chkReproAleatoria;
    private javax.swing.JRadioButton chkReproSequencial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollBar jScrollBar3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSlider jTemps;
    private javax.swing.JList llstAlbums;
    private javax.swing.JList llstBiblioteca;
    private javax.swing.JList llstImatgesAlbum;
    // End of variables declaration//GEN-END:variables
    
                                 /**
    * Mètode que omple la llista de la biblioteca
    * 
    */
    private void omplirLlistaBiblioteca() {
        DefaultListModel model = new DefaultListModel();
        model.clear();
        for(FitxerImatge item: controlador.visualitzarBiblioteca().getLlistaImatge()){
            model.addElement(item);
        }
       llstBiblioteca.setModel(model);
    }
                                     /**
    * Mètode que omple la llista d'àlbums
    * 
    */
    private void omplirLlistaAlbums() {
        DefaultListModel model = new DefaultListModel();
        model.clear();
        for(Album item: controlador.getArrayAlbums()){
            model.addElement(item);
        }
       llstAlbums.setModel(model);
    }
                                     /**
    * Mètode que omple la llista d'imatges de l'àlbum seleccionat
    * @param Album n, que es l'àlbum del que mostrar les imatges
    */
    private void omplirLlistaImatgesAlbums(Album n) {
        DefaultListModel model = new DefaultListModel();
        model.clear();
        for(FitxerImatge item: controlador.veureAlbum(n.getNom()).getLlistaImatge()){
            model.addElement(item);
        }
       llstImatgesAlbum.setModel(model);
    }
                                     /**
    * Mètode que buida la llista d'imatges de l'àlbum
    * 
    */
    private void buidarLlistaImatgesAlbums() {
        DefaultListModel model = new DefaultListModel();
        model.clear();
        llstImatgesAlbum.setModel(model);
    }

    
}
